### ISSUE TITLE
Exchange the Inspector for a new Animation Interface

### ISSUE THREAD

**Issue by linusha** [hpi-swa-lab/qinoq#1054]
Tools inside of lively.next, such as qinoq, should be better integrated with lively.next sidebars. On the other hand, the sidebars will allow for "tool customized hacking" in the future.

For qinoq specifically, the inspector replicates a lot of behavior of the Styling Palette. Getting rid of the inspector would make the tool itself more lean while driving users to use the Styling Palette and benefit from future changes in it.

However, there is one great distinction between qinoqs inspector and the Styling Palette, which is the Inspectors ability to define keyframes and subsequently animations. When getting rid of the value widgets, there needs to be an alternative workflow for this.

## Roadmap

- [x] Remove the value widgets and all related code while keeping everything working
- [x] Integrate "custom halo" and "super halo" in lively.next and use the custom halo reliably in qinoq interactives when editing those. The halo is **the** tool to bind the Styling Palette
- [x] Define and think of a new Animations Layout

## Open Questions

- ~~What to do with the changes indicator?~~ They currently just stay.

This is very open to discussions and input from all sides!
